"""initial schema

Revision ID: c059764ee166
Revises: 
Create Date: 2026-06-08 10:58:27.343854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c059764ee166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_framework', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default=sa.text("'free'"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('classification_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_system_rule', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=True),
    sa.Column('article_reference', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('applies_to_risk_tiers', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'viewer'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('external_idp_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=True),
    sa.Column('asset_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('requested_duration_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('resource_name', sa.String(length=500), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_org', 'audit_logs', ['org_id'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_time', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('data_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('scope_asset_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('scope_asset_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('scope_sensitivity_levels', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_schedule', sa.String(length=50), server_default=sa.text("'0 2 * * *'"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'connected'"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('steward_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_term_id', sa.UUID(), nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_term_id'], ['glossary_terms.id'], ),
    sa.ForeignKeyConstraint(['steward_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_glossary_name')
    )
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('business_domain', sa.String(length=255), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), server_default=sa.text("'unclassified'"), nullable=False),
    sa.Column('risk_assessment_status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('deployment_status', sa.String(length=50), server_default=sa.text("'development'"), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('steward_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=50), server_default=sa.text("'unclassified'"), nullable=False),
    sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steward_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source_id', 'external_id', name='uq_asset_external')
    )
    op.create_index('idx_assets_org', 'assets', ['org_id'], unique=False)
    op.create_index('idx_assets_parent', 'assets', ['parent_id'], unique=False)
    op.create_index('idx_assets_sensitivity', 'assets', ['sensitivity_level'], unique=False)
    op.create_index('idx_assets_source', 'assets', ['source_id'], unique=False)
    op.create_index('idx_assets_type', 'assets', ['asset_type'], unique=False)
    op.create_table('ai_model_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('external_version_id', sa.String(length=500), nullable=True),
    sa.Column('trained_by', sa.UUID(), nullable=True),
    sa.Column('training_dataset_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('training_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=50), server_default=sa.text("'development'"), nullable=False),
    sa.Column('validation_status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('detected_category', sa.String(length=100), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['classification_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('evidence_links', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('source_asset_id', sa.UUID(), nullable=True),
    sa.Column('target_asset_id', sa.UUID(), nullable=True),
    sa.Column('transformation_asset_id', sa.UUID(), nullable=True),
    sa.Column('lineage_type', sa.String(length=50), server_default=sa.text("'technical'"), nullable=False),
    sa.Column('transformation_logic', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transformation_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lineage_source', 'lineage_edges', ['source_asset_id'], unique=False)
    op.create_index('idx_lineage_target', 'lineage_edges', ['target_asset_id'], unique=False)
    op.create_table('quality_check_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('total_rules', sa.Integer(), nullable=True),
    sa.Column('passed_rules', sa.Integer(), nullable=True),
    sa.Column('failed_rules', sa.Integer(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('questionnaire_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('eu_ai_act_category', sa.String(length=100), nullable=True),
    sa.Column('risk_factors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('required_actions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_asset_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('linked_by', sa.UUID(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['glossary_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'asset_id', name='uq_term_asset')
    )
    op.create_table('bias_test_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('test_dataset_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('protected_attributes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('label_column', sa.String(length=255), nullable=True),
    sa.Column('prediction_column', sa.String(length=255), nullable=True),
    sa.Column('positive_label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'running'"), nullable=False),
    sa.Column('overall_bias_verdict', sa.String(length=20), nullable=True),
    sa.Column('demographic_parity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equal_opportunity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predictive_parity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('individual_fairness_score', sa.Float(), nullable=True),
    sa.Column('summary_report', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['ai_model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_dataset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('check_interval_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('psi_threshold', sa.Float(), server_default=sa.text('0.2'), nullable=False),
    sa.Column('accuracy_degradation_threshold', sa.Float(), server_default=sa.text('0.05'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['ai_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_check_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_evaluated', sa.BigInteger(), nullable=True),
    sa.Column('records_failed', sa.BigInteger(), nullable=True),
    sa.Column('failure_percentage', sa.Float(), nullable=True),
    sa.Column('sample_failures', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['quality_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['quality_check_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('monitoring_config_id', sa.UUID(), nullable=True),
    sa.Column('drift_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('affected_features', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('detection_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['ai_model_versions.id'], ),
    sa.ForeignKeyConstraint(['monitoring_config_id'], ['monitoring_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drift_alerts')
    op.drop_table('quality_check_results')
    op.drop_table('monitoring_configs')
    op.drop_table('bias_test_runs')
    op.drop_table('term_asset_links')
    op.drop_table('risk_assessments')
    op.drop_table('quality_rules')
    op.drop_table('quality_check_runs')
    op.drop_index('idx_lineage_target', table_name='lineage_edges')
    op.drop_index('idx_lineage_source', table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_table('compliance_mappings')
    op.drop_table('classification_results')
    op.drop_table('ai_model_versions')
    op.drop_index('idx_assets_type', table_name='assets')
    op.drop_index('idx_assets_source', table_name='assets')
    op.drop_index('idx_assets_sensitivity', table_name='assets')
    op.drop_index('idx_assets_parent', table_name='assets')
    op.drop_index('idx_assets_org', table_name='assets')
    op.drop_table('assets')
    op.drop_table('ai_models')
    op.drop_table('glossary_terms')
    op.drop_table('data_sources')
    op.drop_table('data_policies')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_time', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_org', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('access_requests')
    op.drop_table('users')
    op.drop_table('compliance_requirements')
    op.drop_table('classification_rules')
    op.drop_table('organizations')
    op.drop_table('compliance_frameworks')
    # ### end Alembic commands ###
